apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: identity-api
  name: identity-api
spec:
  ports:
  - name: "1421"
    port: 1421
    targetPort: 80
  selector:
    io.kompose.service: identity-api
status:
  loadBalancer: {}
