apiVersion: v1
kind: ConfigMap
metadata:
  name: identityapi-configmap
data:
  # property-like keys; each key maps to a simple value
  connection_string: "Server=identityapi-db-nodeport;Database=identity-api-db;User=sa;Password=password123!;"
  rabbitmq_hostname: "rabbitmq-nodeport"