apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: identity-api-db
  name: identity-api-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: identity-api-db
  template:
    metadata:
      labels:
        io.kompose.service: identity-api-db
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "password123!"
        image: mcr.microsoft.com/mssql/server:2019-latest
        name: identity-api-db
        ports:
        - containerPort: 1433
        resources: {}
      restartPolicy: Always
status: {}
