apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: identity-api-db
  name: identity-api-db
spec:
  ports:
  - name: "1401"
    port: 1401
    targetPort: 1433
  selector:
    io.kompose.service: identity-api-db
status:
  loadBalancer: {}
