apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: machinelearning-api
  name: machinelearning-api
spec:
  ports:
  - name: "1422"
    port: 1422
    targetPort: 80
  selector:
    io.kompose.service: machinelearning-api
status:
  loadBalancer: {}
