apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: machinelearning-api-db
  name: machinelearning-api-db
spec:
  ports:
  - name: "1402"
    port: 1402
    targetPort: 1433
  selector:
    io.kompose.service: machinelearning-api-db
status:
  loadBalancer: {}
