apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: payment-api
  name: payment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: payment-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: payment-api
        deploy: v6_2
    spec:
      containers:
      - image: rsazor12/paymentapi:v2
        imagePullPolicy: ""
        name: payment-api
        env:
          - name: AppSettings__ConnectionStrings__DefaultConnection
            valueFrom:
              configMapKeyRef:
                name: paymentapi-configmap
                key: connection_string
          - name: AppSettings__EventBusHostName
            valueFrom:
              configMapKeyRef:
                name: paymentapi-configmap
                key: rabbitmq_hostname
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
