apiVersion: v1
kind: Service
metadata:
  name: payment-api-db-nodeport
spec:
  type: NodePort
  selector:
    io.kompose.service: payment-api-db
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 1433
      targetPort: 1433
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 31434